version: '3'
services:
  backend:
    build: backend/
    environment:
      APPID: ${APP_ID}
    networks:
    - weatherapp
  frontend:
    build: 
      context: frontend/
      args:
        ENDPOINT: /api
    depends_on:
    - backend
    ports:
    - 8080:80
    networks:
    - weatherapp
networks:
  weatherapp:
